#!/usr/bin/env python3

import argparse, sys
from urllib.parse import quote_plus

class ludicrousspeed:
    def __init__(self, bing, duckduckgo, google, verbose, excludeai, query):
        self.verbose = verbose
        self._debug("Parsing variables.")
        self.bing = bing
        self.duckduckgo = duckduckgo
        self.google = google
        self.excludeai = excludeai
        self.query = quote_plus(query)
        self._debug("Variables parsed.")

    def _google(self):
        self._debug("Executing translation for Google.")
        if self.excludeai:
            self._debug("Ensuring AI is not used in query.")
            self._info("https://google.com?udm=14&q="+self.query)
        else:
            self._info("https://google.com?q="+self.query)
        return None

    def _bing(self):
        self._debug("Executing translation for Bing.")
        if self.excludeai:
            self._debug("Ensuring AI is not used in query.")
            self._info("https://bing.com/search?copilot=off&q="+self.query)
        else:
            self._info("https://bing.com/search?q="+self.query)
        return None

    def _duckduckgo(self):
        self._debug("Executing translation for DuckDuckGo.")
        if self.excludeai:
            self._debug("Ensuring AI is not used in query.")
            self._info("https://noai.duckduckgo.com?q="+self.query)
        else:
            self._info("https://duckduckgo.com?q="+self.query)
        return None
    
    def _debug(self, debugstring):
        if self.verbose:
            print("VERBOSE: "+debugstring)
        return None

    def _info(self, infostring):
        if self.verbose:
            print("   INFO: "+infostring)
        else:
            print(infostring)
            return None

    def run(self):
        flags=0
        self._debug("Checking if Bing is requested.")
        if self.bing:
            flags+=1
            self._bing()
        self._debug("Checking if DuckDuckGo is reqeusted.")
        if self.duckduckgo:
            flags+=1
            self._duckduckgo()
        # Default option
        self._debug("Checking if Google is requested or if no other options were requested.")
        if self.google or flags <= 0:
            self._google()
        self._debug("Ending program.")
        return None

parser = argparse.ArgumentParser(
    prog='c',
    description='Takes in a query and returns a URL to a search engine for your query.'
)
parser.add_argument('-b', '--bing', action='store_true', help='Calculates Bing URL.')
parser.add_argument('-d', '--duckduckgo', action='store_true', help='Calculates DuckDuckGo URL.')
parser.add_argument('-g', '--google', action='store_true', help='Calculates Google URL (default functionality).')
parser.add_argument('-v', '--verbose', action='store_true', help='Verbose')
parser.add_argument('-x', '--excludeai', action='store_true', help='Exclude AI results (where applicable).')
parser.add_argument('-y', '--yogurt', action='store_true', help='Expresses opinions on Yogurt during query.')
parser.add_argument('query', help='Query you wish to ask the AI gods.')
args = parser.parse_args()

if __name__ == "__main__":
    if args.yogurt:
        yogurtstring="Yogurt! Yogurt! I hate Yogurt! Even with strawberries!"
        if args.verbose: print("VERBOSE: Expressing opintions on Yogurt.")
        print("   INFO: "+yogurtstring if args.verbose else yogurtstring)
    try:
        if args.verbose: print("VERBOSE: Executing query conversion.")
        execution = ludicrousspeed(args.bing, args.duckduckgo, args.google, args.verbose, args.excludeai, args.query)
        execution.run()

    except:
        plaidstring="You've gone to plaid!"
        if args.verbose: print("VERBOSE: Error occured.")
        print("   INFO: "+plaidstring if args.verbose else plaidstring)
        sys.exit(1)
if args.verbose: print("VERBOSE: Program completed successfully, exiting.")
sys.exit(0)